# Generated by Django 4.2.30 on 2026-05-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated Timestamp'),
        ),
    ]
