# Generated by Django 4.2.30 on 2026-05-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_management', '0002_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Name')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Industry Type')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Person')),
                ('contract_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Contract Value')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated')], default='Active', max_length=20, verbose_name='Partnership Status')),
                ('projects', models.TextField(blank=True, help_text='Comma-separated project IDs list tracker definitions', null=True, verbose_name='Linked Projects Array')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Record',
                'verbose_name_plural': 'Client Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
