# Generated by Django 4.2.30 on 2026-05-21 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_management', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product ID')),
                ('license_type', models.CharField(choices=[('Trial', 'Trial'), ('Standard', 'Standard'), ('Premium', 'Premium'), ('Enterprise', 'Enterprise')], default='Standard', max_length=30, verbose_name='License Type')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='License Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='License End Date')),
                ('support_level', models.CharField(choices=[('L1', 'L1 Support'), ('L2', 'L2 Support'), ('L3', 'L3 Support')], default='L1', max_length=10, verbose_name='Technical Support Level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_licences', to='core_management.client', verbose_name='Licensed Client')),
            ],
            options={
                'verbose_name': 'Licensed Product Client',
                'verbose_name_plural': 'Licensed Product Clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
