# Generated by Django 4.2.30 on 2026-05-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_management', '0004_productclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclient',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Name'),
        ),
    ]
