# Generated by Django 4.2.30 on 2026-05-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_management', '0005_productclient_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_details',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Personal JSON Details Matrix'),
        ),
    ]
