# Generated by Django 4.2.30 on 2026-05-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_management', '0006_user_personal_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('admin', 'Administrator'), ('hr', 'HR Manager'), ('lobby', 'Lobby Desk'), ('bgv_officer', 'BGV Officer')], default='employee', max_length=20, verbose_name='System Role'),
        ),
    ]
