# Generated by Django 4.2.30 on 2026-05-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_management', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passport_doc',
            field=models.FileField(blank=True, null=True, upload_to='employee_assets/documents/passports/', verbose_name='Passport Document'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_assets/photos/', verbose_name='ID Badge Profile Photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='tenth_certificate_doc',
            field=models.FileField(blank=True, null=True, upload_to='employee_assets/documents/certificates/', verbose_name='10th Marksheet Certificate'),
        ),
    ]
