# Generated by Django 4.2.30 on 2026-05-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_management', '0008_user_passport_doc_user_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar_card_doc',
            field=models.FileField(blank=True, null=True, upload_to='employee_assets/documents/aadhar/', verbose_name='Aadhar Card'),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_card_doc',
            field=models.FileField(blank=True, null=True, upload_to='employee_assets/documents/pan/', verbose_name='PAN Card'),
        ),
        migrations.AddField(
            model_name='user',
            name='tenth_marksheet_doc',
            field=models.FileField(blank=True, null=True, upload_to='employee_assets/documents/certificates_10th/', verbose_name='10th Marksheet'),
        ),
        migrations.AddField(
            model_name='user',
            name='twelfth_marksheet_doc',
            field=models.FileField(blank=True, null=True, upload_to='employee_assets/documents/certificates_12th/', verbose_name='12th Marksheet'),
        ),
    ]
