# Generated by Django 4.2.30 on 2026-05-21 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BGVWorkflowCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_stage', models.CharField(choices=[('Initiated', 'Initiated / Received'), ('Document Review', 'Document Under Review'), ('Approved', 'Passed / Cleared'), ('Rejected', 'Flagged / Failed')], default='Initiated', max_length=30)),
                ('source_email', models.EmailField(max_length=254, verbose_name='Sender Email Address')),
                ('email_message_id', models.CharField(max_length=255, unique=True, verbose_name='Unique Email UID')),
                ('aadhar_file', models.FileField(blank=True, null=True, upload_to='bgv_documents/aadhar/')),
                ('pan_file', models.FileField(blank=True, null=True, upload_to='bgv_documents/pan/')),
                ('marksheet_file', models.FileField(blank=True, null=True, upload_to='bgv_documents/marksheets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bgv_checks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
