# Generated by Django 4.2.30 on 2026-05-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgv_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownCandidateBGVCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255, verbose_name='Extracted Sender Name')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='Sender Gmail Address')),
                ('email_message_id', models.CharField(max_length=255, unique=True)),
                ('workflow_stage', models.CharField(choices=[('Initiated', 'Received / Awaiting Review'), ('Dispatched', 'Sent to BGV Officer')], default='Initiated', max_length=30)),
                ('aadhar_file', models.FileField(blank=True, null=True, upload_to='bgv_system/aadhar/')),
                ('pan_file', models.FileField(blank=True, null=True, upload_to='bgv_system/pan/')),
                ('marksheet_file', models.FileField(blank=True, null=True, upload_to='bgv_system/marksheets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
