# Generated by Django 4.2.30 on 2026-05-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgv_system', '0002_unknowncandidatebgvcheck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unknowncandidatebgvcheck',
            options={'ordering': ['-created_at'], 'verbose_name': 'Unknown Candidate BGV Check', 'verbose_name_plural': 'Unknown Candidate BGV Checks'},
        ),
        migrations.RemoveField(
            model_name='unknowncandidatebgvcheck',
            name='aadhar_file',
        ),
        migrations.RemoveField(
            model_name='unknowncandidatebgvcheck',
            name='email_message_id',
        ),
        migrations.RemoveField(
            model_name='unknowncandidatebgvcheck',
            name='pan_file',
        ),
        migrations.RemoveField(
            model_name='unknowncandidatebgvcheck',
            name='sender_email',
        ),
        migrations.RemoveField(
            model_name='unknowncandidatebgvcheck',
            name='sender_name',
        ),
        migrations.RemoveField(
            model_name='unknowncandidatebgvcheck',
            name='workflow_stage',
        ),
        migrations.AddField(
            model_name='unknowncandidatebgvcheck',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Aadhaar Number'),
        ),
        migrations.AddField(
            model_name='unknowncandidatebgvcheck',
            name='course_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course / Degree Type'),
        ),
        migrations.AddField(
            model_name='unknowncandidatebgvcheck',
            name='experience_file',
            field=models.FileField(blank=True, null=True, upload_to='candidate_documents/experience/'),
        ),
        migrations.AddField(
            model_name='unknowncandidatebgvcheck',
            name='is_sent_to_bgv',
            field=models.BooleanField(default=False, verbose_name='Sent to BGV Agency Status'),
        ),
        migrations.AddField(
            model_name='unknowncandidatebgvcheck',
            name='pan',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PAN Card Number'),
        ),
        migrations.AddField(
            model_name='unknowncandidatebgvcheck',
            name='submission_id',
            field=models.CharField(default='TEMP-REF', max_length=50, unique=True, verbose_name='Submission Reference ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unknowncandidatebgvcheck',
            name='marksheet_file',
            field=models.FileField(blank=True, null=True, upload_to='candidate_documents/marksheets/'),
        ),
    ]
