# Generated by Django 4.2.30 on 2026-05-22 06:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bgv_system', '0003_alter_unknowncandidatebgvcheck_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unknowncandidatebgvcheck',
            name='is_verified_by_officer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unknowncandidatebgvcheck',
            name='submission_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
    ]
