# Generated by Django 4.2.30 on 2026-05-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_client', '0002_snoozedemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_account', models.CharField(max_length=255, unique=True)),
                ('emails_per_page', models.IntegerField(default=50)),
                ('inbox_type', models.CharField(default='default', max_length=50)),
                ('display_density', models.CharField(default='default', max_length=50)),
                ('theme', models.CharField(default='light', max_length=50)),
            ],
        ),
    ]
