# Generated by Django 4.2.30 on 2026-05-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_client', '0003_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='text_size',
            field=models.CharField(default='Normal', max_length=20),
        ),
    ]
