# Generated by Django 4.2.30 on 2026-05-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_client', '0004_usersettings_text_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('folder', models.CharField(default='INBOX', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
