# Generated by Django 4.2.30 on 2026-05-21 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_client', '0007_policydocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PolicyDocument',
        ),
    ]
