# Generated by Django 4.2.30 on 2026-05-21 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=255, verbose_name='Project ID / Name')),
                ('change_description', models.TextField(verbose_name='Change Description')),
                ('impact', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=20, verbose_name='Impact Level')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Status')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Effective Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Change Plan',
                'verbose_name_plural': 'Change Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=255, verbose_name='Project ID / Name')),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Allocated Budget')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Actual Cost Incurred')),
                ('resource_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Human Resource Cost')),
                ('travel_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Travel & Transport Cost')),
                ('variance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, verbose_name='Budget Variance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cost Monitoring Record',
                'verbose_name_plural': 'Cost Monitoring Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=255, verbose_name='Policy Name')),
                ('category', models.CharField(choices=[('HR', 'HR'), ('IT', 'IT'), ('Security', 'Security'), ('Financial', 'Financial'), ('General', 'General')], max_length=20, verbose_name='Category')),
                ('version', models.CharField(default='1.0', max_length=50, verbose_name='Version')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Effective Date')),
                ('document_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Document Path/Link')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Archived', 'Archived')], default='Active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Policy Hub Record',
                'verbose_name_plural': 'Policy Hub Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_type', models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International')], max_length=20, verbose_name='Travel Type')),
                ('from_location', models.CharField(max_length=255, verbose_name='From Location')),
                ('to_location', models.CharField(max_length=255, verbose_name='To Location')),
                ('purpose', models.TextField(blank=True, null=True, verbose_name='Purpose')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Estimated Cost')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20, verbose_name='Status')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Departure Date')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Return Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_travel_requests', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Travel Request',
                'verbose_name_plural': 'Travel Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issuing_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=255, null=True)),
                ('credential_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('certification_name', models.CharField(blank=True, max_length=255, null=True)),
                ('provider', models.CharField(blank=True, max_length=255, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('validity', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bench',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(blank=True, max_length=500, null=True, verbose_name='Skills')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bench_allocations', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Bench Record',
                'verbose_name_plural': 'Bench Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
