# Generated by Django 4.2.30 on 2026-05-21 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50, verbose_name='Vehicle Number')),
                ('vehicle_type', models.CharField(choices=[('2-Wheeler', '2-Wheeler'), ('4-Wheeler', '4-Wheeler')], default='2-Wheeler', max_length=20, verbose_name='Vehicle Type')),
                ('parking_slot', models.CharField(blank=True, max_length=50, null=True, verbose_name='Parking Slot/Bay')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid Until')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Revoked', 'Revoked')], default='Active', max_length=20, verbose_name='Pass Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_passes', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Vehicle Pass',
                'verbose_name_plural': 'Vehicle Passes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeatAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_id', models.CharField(max_length=50, unique=True, verbose_name='Seat ID')),
                ('floor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Floor')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('allocation_date', models.DateField(blank=True, null=True, verbose_name='Allocation Date')),
                ('status', models.CharField(choices=[('Allocated', 'Allocated'), ('Vacant', 'Vacant'), ('Maintenance', 'Maintenance')], default='Vacant', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_allocations', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Employee')),
            ],
            options={
                'ordering': ['seat_id'],
            },
        ),
        migrations.CreateModel(
            name='CafeteriaComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('Food Quality', 'Food Quality'), ('Hygiene', 'Hygiene'), ('Staff Behavior', 'Staff Behavior'), ('Service Delay', 'Service Delay'), ('Other', 'Other')], max_length=50, verbose_name='Complaint Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Logged')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Addressed', 'Addressed'), ('Resolved', 'Resolved')], default='Pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafeteria_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Asset ID')),
                ('asset_type', models.CharField(choices=[('Laptop', 'Laptop'), ('Monitor', 'Monitor'), ('Phone', 'Phone'), ('Other', 'Other')], max_length=20, verbose_name='Asset Type')),
                ('serial_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial Number')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('In Repair', 'In Repair'), ('Scrapped', 'Scrapped')], default='Available', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_assets', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
