# Generated by Django 4.2.30 on 2026-05-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='college_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='passed_out_year',
            field=models.IntegerField(null=True),
        ),
    ]
