# Generated by Django 4.2.30 on 2026-05-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_management', '0002_alter_visitor_college_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='passed_out_year',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
